-- LV2. 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(*) AS "COUNT" 
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE;

-- LV2. 동명 동물 수 찾기
SELECT NAME, COUNT(NAME) AS "COUNT"
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME)>1
ORDER BY NAME;

-- LV2. 입양 시각 구하기(1)
SELECT DATE_FORMAT(DATETIME, "%H") AS "HOUR", COUNT(DATETIME) AS "COUNT"
FROM ANIMAL_OUTS
GROUP BY DATE_FORMAT(DATETIME, "%H")
HAVING HOUR >=9 AND HOUR <=19
ORDER BY DATE_FORMAT(DATETIME, "%H");

-- LV4. 입양 시각 구하기(2)
