-- LV3. 없어진 기록 찾기
SELECT DISTINCT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE O.ANIMAL_ID NOT IN
    (SELECT ANIMAL_ID
    FROM ANIMAL_INS)
ORDER BY O.ANIMAL_ID;

-- LV3. 있었는데요 없었습니다
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME;

-- LV3. 오랜 기간 보호한 동물(1)
SELECT DISTINCT I.NAME, I.DATETIME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY I.DATETIME LIMIT 3;

-- LV4. 보호소에서 중성화한 동물
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE I.ANIMAL_ID = O.ANIMAL_ID  
    AND I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME
   -- AND I.SEX_UPON_INTAKE LIKE "IN%" 
   -- AND (O.SEX_UPON_OUTCOME LIKE "SP%" OR O.SEX_UPON_OUTCOME LIKE "NE%")
ORDER BY I.ANIMAL_ID;
