-- LV1. 최댓값 구하기
SELECT DATETIME "시간" FROM ANIMAL_INS
ORDER BY DATETIME DESC
LIMIT 1;

-- LV2. 최솟값 구하기
SELECT MIN(DATETIME)as '시간' FROM ANIMAL_INS

-- LV2. 동물 수 구하기
SELECT COUNT(*) AS "count" FROM ANIMAL_INS

-- LV2. 중복 제거하기
SELECT COUNT(DISTINCT NAME) AS "COUNT" FROM ANIMAL_INS
WHERE NAME != 'NULL';
